spring.application.name=demo
spring.datasource.url=jdbc:mariadb://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

# JWT
jwt.secret-key=BC5BDCEBDED8093C0755C983EC4E47F482C5AEFB0412943C152F53D2C865CDC3

